### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by webfolderio** [protobufel/multikeymapjava#10]
Hi,

Is this library thread safe?

Thanks

**Comment by protobufel** [comment]
1. In short, no. This is by design. You can, as usual, use any Java external synchronization techniques, including  java.util.Collections.synchronizedMap(yourMultiKeyMap). 
2. For optimized stream processing, you may choose newMultiKeyMap(mapSupplier, concurrent) factory method which uses the Java's ConcurrentHashMap behind the scene which may improve performance in some cases. Still, you might want to use external synchronization as above.

Hope this helps,
David

**Comment by webfolderio** [comment]
Thans for the clatification.
